/**
 * Autogenerated by Thrift Compiler (0.12.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package edu.zju.supersql.rpc;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
/**
 * 显式最终决议状态（用于跨节点确认日志最终语义）
 */
@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.12.0)", date = "2026-04-19")
public class LogDecisionState implements org.apache.thrift.TBase<LogDecisionState, LogDecisionState._Fields>, java.io.Serializable, Cloneable, Comparable<LogDecisionState> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("LogDecisionState");

  private static final org.apache.thrift.protocol.TField DECIDED_FIELD_DESC = new org.apache.thrift.protocol.TField("decided", org.apache.thrift.protocol.TType.BOOL, (short)1);
  private static final org.apache.thrift.protocol.TField COMMITTED_FIELD_DESC = new org.apache.thrift.protocol.TField("committed", org.apache.thrift.protocol.TType.BOOL, (short)2);
  private static final org.apache.thrift.protocol.TField DECISION_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("decisionId", org.apache.thrift.protocol.TType.STRING, (short)3);
  private static final org.apache.thrift.protocol.TField DECIDED_AT_MS_FIELD_DESC = new org.apache.thrift.protocol.TField("decidedAtMs", org.apache.thrift.protocol.TType.I64, (short)4);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new LogDecisionStateStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new LogDecisionStateTupleSchemeFactory();

  private boolean decided; // required
  private boolean committed; // optional
  private @org.apache.thrift.annotation.Nullable java.lang.String decisionId; // optional
  private long decidedAtMs; // optional

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    DECIDED((short)1, "decided"),
    COMMITTED((short)2, "committed"),
    DECISION_ID((short)3, "decisionId"),
    DECIDED_AT_MS((short)4, "decidedAtMs");

    private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // DECIDED
          return DECIDED;
        case 2: // COMMITTED
          return COMMITTED;
        case 3: // DECISION_ID
          return DECISION_ID;
        case 4: // DECIDED_AT_MS
          return DECIDED_AT_MS;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __DECIDED_ISSET_ID = 0;
  private static final int __COMMITTED_ISSET_ID = 1;
  private static final int __DECIDEDATMS_ISSET_ID = 2;
  private byte __isset_bitfield = 0;
  private static final _Fields optionals[] = {_Fields.COMMITTED,_Fields.DECISION_ID,_Fields.DECIDED_AT_MS};
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.DECIDED, new org.apache.thrift.meta_data.FieldMetaData("decided", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.BOOL)));
    tmpMap.put(_Fields.COMMITTED, new org.apache.thrift.meta_data.FieldMetaData("committed", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.BOOL)));
    tmpMap.put(_Fields.DECISION_ID, new org.apache.thrift.meta_data.FieldMetaData("decisionId", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.DECIDED_AT_MS, new org.apache.thrift.meta_data.FieldMetaData("decidedAtMs", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64)));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(LogDecisionState.class, metaDataMap);
  }

  public LogDecisionState() {
  }

  public LogDecisionState(
    boolean decided)
  {
    this();
    this.decided = decided;
    setDecidedIsSet(true);
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public LogDecisionState(LogDecisionState other) {
    __isset_bitfield = other.__isset_bitfield;
    this.decided = other.decided;
    this.committed = other.committed;
    if (other.isSetDecisionId()) {
      this.decisionId = other.decisionId;
    }
    this.decidedAtMs = other.decidedAtMs;
  }

  public LogDecisionState deepCopy() {
    return new LogDecisionState(this);
  }

  @Override
  public void clear() {
    setDecidedIsSet(false);
    this.decided = false;
    setCommittedIsSet(false);
    this.committed = false;
    this.decisionId = null;
    setDecidedAtMsIsSet(false);
    this.decidedAtMs = 0;
  }

  public boolean isDecided() {
    return this.decided;
  }

  public void setDecided(boolean decided) {
    this.decided = decided;
    setDecidedIsSet(true);
  }

  public void unsetDecided() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __DECIDED_ISSET_ID);
  }

  /** Returns true if field decided is set (has been assigned a value) and false otherwise */
  public boolean isSetDecided() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __DECIDED_ISSET_ID);
  }

  public void setDecidedIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __DECIDED_ISSET_ID, value);
  }

  public boolean isCommitted() {
    return this.committed;
  }

  public void setCommitted(boolean committed) {
    this.committed = committed;
    setCommittedIsSet(true);
  }

  public void unsetCommitted() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __COMMITTED_ISSET_ID);
  }

  /** Returns true if field committed is set (has been assigned a value) and false otherwise */
  public boolean isSetCommitted() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __COMMITTED_ISSET_ID);
  }

  public void setCommittedIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __COMMITTED_ISSET_ID, value);
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.String getDecisionId() {
    return this.decisionId;
  }

  public void setDecisionId(@org.apache.thrift.annotation.Nullable java.lang.String decisionId) {
    this.decisionId = decisionId;
  }

  public void unsetDecisionId() {
    this.decisionId = null;
  }

  /** Returns true if field decisionId is set (has been assigned a value) and false otherwise */
  public boolean isSetDecisionId() {
    return this.decisionId != null;
  }

  public void setDecisionIdIsSet(boolean value) {
    if (!value) {
      this.decisionId = null;
    }
  }

  public long getDecidedAtMs() {
    return this.decidedAtMs;
  }

  public void setDecidedAtMs(long decidedAtMs) {
    this.decidedAtMs = decidedAtMs;
    setDecidedAtMsIsSet(true);
  }

  public void unsetDecidedAtMs() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __DECIDEDATMS_ISSET_ID);
  }

  /** Returns true if field decidedAtMs is set (has been assigned a value) and false otherwise */
  public boolean isSetDecidedAtMs() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __DECIDEDATMS_ISSET_ID);
  }

  public void setDecidedAtMsIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __DECIDEDATMS_ISSET_ID, value);
  }

  public void setFieldValue(_Fields field, @org.apache.thrift.annotation.Nullable java.lang.Object value) {
    switch (field) {
    case DECIDED:
      if (value == null) {
        unsetDecided();
      } else {
        setDecided((java.lang.Boolean)value);
      }
      break;

    case COMMITTED:
      if (value == null) {
        unsetCommitted();
      } else {
        setCommitted((java.lang.Boolean)value);
      }
      break;

    case DECISION_ID:
      if (value == null) {
        unsetDecisionId();
      } else {
        setDecisionId((java.lang.String)value);
      }
      break;

    case DECIDED_AT_MS:
      if (value == null) {
        unsetDecidedAtMs();
      } else {
        setDecidedAtMs((java.lang.Long)value);
      }
      break;

    }
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.Object getFieldValue(_Fields field) {
    switch (field) {
    case DECIDED:
      return isDecided();

    case COMMITTED:
      return isCommitted();

    case DECISION_ID:
      return getDecisionId();

    case DECIDED_AT_MS:
      return getDecidedAtMs();

    }
    throw new java.lang.IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new java.lang.IllegalArgumentException();
    }

    switch (field) {
    case DECIDED:
      return isSetDecided();
    case COMMITTED:
      return isSetCommitted();
    case DECISION_ID:
      return isSetDecisionId();
    case DECIDED_AT_MS:
      return isSetDecidedAtMs();
    }
    throw new java.lang.IllegalStateException();
  }

  @Override
  public boolean equals(java.lang.Object that) {
    if (that == null)
      return false;
    if (that instanceof LogDecisionState)
      return this.equals((LogDecisionState)that);
    return false;
  }

  public boolean equals(LogDecisionState that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_decided = true;
    boolean that_present_decided = true;
    if (this_present_decided || that_present_decided) {
      if (!(this_present_decided && that_present_decided))
        return false;
      if (this.decided != that.decided)
        return false;
    }

    boolean this_present_committed = true && this.isSetCommitted();
    boolean that_present_committed = true && that.isSetCommitted();
    if (this_present_committed || that_present_committed) {
      if (!(this_present_committed && that_present_committed))
        return false;
      if (this.committed != that.committed)
        return false;
    }

    boolean this_present_decisionId = true && this.isSetDecisionId();
    boolean that_present_decisionId = true && that.isSetDecisionId();
    if (this_present_decisionId || that_present_decisionId) {
      if (!(this_present_decisionId && that_present_decisionId))
        return false;
      if (!this.decisionId.equals(that.decisionId))
        return false;
    }

    boolean this_present_decidedAtMs = true && this.isSetDecidedAtMs();
    boolean that_present_decidedAtMs = true && that.isSetDecidedAtMs();
    if (this_present_decidedAtMs || that_present_decidedAtMs) {
      if (!(this_present_decidedAtMs && that_present_decidedAtMs))
        return false;
      if (this.decidedAtMs != that.decidedAtMs)
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + ((decided) ? 131071 : 524287);

    hashCode = hashCode * 8191 + ((isSetCommitted()) ? 131071 : 524287);
    if (isSetCommitted())
      hashCode = hashCode * 8191 + ((committed) ? 131071 : 524287);

    hashCode = hashCode * 8191 + ((isSetDecisionId()) ? 131071 : 524287);
    if (isSetDecisionId())
      hashCode = hashCode * 8191 + decisionId.hashCode();

    hashCode = hashCode * 8191 + ((isSetDecidedAtMs()) ? 131071 : 524287);
    if (isSetDecidedAtMs())
      hashCode = hashCode * 8191 + org.apache.thrift.TBaseHelper.hashCode(decidedAtMs);

    return hashCode;
  }

  @Override
  public int compareTo(LogDecisionState other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = java.lang.Boolean.valueOf(isSetDecided()).compareTo(other.isSetDecided());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetDecided()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.decided, other.decided);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetCommitted()).compareTo(other.isSetCommitted());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetCommitted()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.committed, other.committed);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetDecisionId()).compareTo(other.isSetDecisionId());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetDecisionId()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.decisionId, other.decisionId);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetDecidedAtMs()).compareTo(other.isSetDecidedAtMs());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetDecidedAtMs()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.decidedAtMs, other.decidedAtMs);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  @org.apache.thrift.annotation.Nullable
  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public java.lang.String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder("LogDecisionState(");
    boolean first = true;

    sb.append("decided:");
    sb.append(this.decided);
    first = false;
    if (isSetCommitted()) {
      if (!first) sb.append(", ");
      sb.append("committed:");
      sb.append(this.committed);
      first = false;
    }
    if (isSetDecisionId()) {
      if (!first) sb.append(", ");
      sb.append("decisionId:");
      if (this.decisionId == null) {
        sb.append("null");
      } else {
        sb.append(this.decisionId);
      }
      first = false;
    }
    if (isSetDecidedAtMs()) {
      if (!first) sb.append(", ");
      sb.append("decidedAtMs:");
      sb.append(this.decidedAtMs);
      first = false;
    }
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    if (!isSetDecided()) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'decided' is unset! Struct:" + toString());
    }

    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class LogDecisionStateStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public LogDecisionStateStandardScheme getScheme() {
      return new LogDecisionStateStandardScheme();
    }
  }

  private static class LogDecisionStateStandardScheme extends org.apache.thrift.scheme.StandardScheme<LogDecisionState> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, LogDecisionState struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // DECIDED
            if (schemeField.type == org.apache.thrift.protocol.TType.BOOL) {
              struct.decided = iprot.readBool();
              struct.setDecidedIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // COMMITTED
            if (schemeField.type == org.apache.thrift.protocol.TType.BOOL) {
              struct.committed = iprot.readBool();
              struct.setCommittedIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // DECISION_ID
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.decisionId = iprot.readString();
              struct.setDecisionIdIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 4: // DECIDED_AT_MS
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.decidedAtMs = iprot.readI64();
              struct.setDecidedAtMsIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, LogDecisionState struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      oprot.writeFieldBegin(DECIDED_FIELD_DESC);
      oprot.writeBool(struct.decided);
      oprot.writeFieldEnd();
      if (struct.isSetCommitted()) {
        oprot.writeFieldBegin(COMMITTED_FIELD_DESC);
        oprot.writeBool(struct.committed);
        oprot.writeFieldEnd();
      }
      if (struct.decisionId != null) {
        if (struct.isSetDecisionId()) {
          oprot.writeFieldBegin(DECISION_ID_FIELD_DESC);
          oprot.writeString(struct.decisionId);
          oprot.writeFieldEnd();
        }
      }
      if (struct.isSetDecidedAtMs()) {
        oprot.writeFieldBegin(DECIDED_AT_MS_FIELD_DESC);
        oprot.writeI64(struct.decidedAtMs);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class LogDecisionStateTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public LogDecisionStateTupleScheme getScheme() {
      return new LogDecisionStateTupleScheme();
    }
  }

  private static class LogDecisionStateTupleScheme extends org.apache.thrift.scheme.TupleScheme<LogDecisionState> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, LogDecisionState struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      oprot.writeBool(struct.decided);
      java.util.BitSet optionals = new java.util.BitSet();
      if (struct.isSetCommitted()) {
        optionals.set(0);
      }
      if (struct.isSetDecisionId()) {
        optionals.set(1);
      }
      if (struct.isSetDecidedAtMs()) {
        optionals.set(2);
      }
      oprot.writeBitSet(optionals, 3);
      if (struct.isSetCommitted()) {
        oprot.writeBool(struct.committed);
      }
      if (struct.isSetDecisionId()) {
        oprot.writeString(struct.decisionId);
      }
      if (struct.isSetDecidedAtMs()) {
        oprot.writeI64(struct.decidedAtMs);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, LogDecisionState struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      struct.decided = iprot.readBool();
      struct.setDecidedIsSet(true);
      java.util.BitSet incoming = iprot.readBitSet(3);
      if (incoming.get(0)) {
        struct.committed = iprot.readBool();
        struct.setCommittedIsSet(true);
      }
      if (incoming.get(1)) {
        struct.decisionId = iprot.readString();
        struct.setDecisionIdIsSet(true);
      }
      if (incoming.get(2)) {
        struct.decidedAtMs = iprot.readI64();
        struct.setDecidedAtMsIsSet(true);
      }
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

