/**
 * Autogenerated by Thrift Compiler (0.16.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package edu.zju.supersql.rpc;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
/**
 * RegionServer 节点信息
 */
@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.16.0)", date = "2026-04-08")
public class RegionServerInfo implements org.apache.thrift.TBase<RegionServerInfo, RegionServerInfo._Fields>, java.io.Serializable, Cloneable, Comparable<RegionServerInfo> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("RegionServerInfo");

  private static final org.apache.thrift.protocol.TField ID_FIELD_DESC = new org.apache.thrift.protocol.TField("id", org.apache.thrift.protocol.TType.STRING, (short)1);
  private static final org.apache.thrift.protocol.TField HOST_FIELD_DESC = new org.apache.thrift.protocol.TField("host", org.apache.thrift.protocol.TType.STRING, (short)2);
  private static final org.apache.thrift.protocol.TField PORT_FIELD_DESC = new org.apache.thrift.protocol.TField("port", org.apache.thrift.protocol.TType.I32, (short)3);
  private static final org.apache.thrift.protocol.TField TABLE_COUNT_FIELD_DESC = new org.apache.thrift.protocol.TField("tableCount", org.apache.thrift.protocol.TType.I32, (short)4);
  private static final org.apache.thrift.protocol.TField QPS1MIN_FIELD_DESC = new org.apache.thrift.protocol.TField("qps1min", org.apache.thrift.protocol.TType.DOUBLE, (short)5);
  private static final org.apache.thrift.protocol.TField CPU_USAGE_FIELD_DESC = new org.apache.thrift.protocol.TField("cpuUsage", org.apache.thrift.protocol.TType.DOUBLE, (short)6);
  private static final org.apache.thrift.protocol.TField MEM_USAGE_FIELD_DESC = new org.apache.thrift.protocol.TField("memUsage", org.apache.thrift.protocol.TType.DOUBLE, (short)7);
  private static final org.apache.thrift.protocol.TField LAST_HEARTBEAT_FIELD_DESC = new org.apache.thrift.protocol.TField("lastHeartbeat", org.apache.thrift.protocol.TType.I64, (short)8);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new RegionServerInfoStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new RegionServerInfoTupleSchemeFactory();

  private @org.apache.thrift.annotation.Nullable java.lang.String id; // required
  private @org.apache.thrift.annotation.Nullable java.lang.String host; // required
  private int port; // required
  private int tableCount; // optional
  private double qps1min; // optional
  private double cpuUsage; // optional
  private double memUsage; // optional
  private long lastHeartbeat; // optional

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    ID((short)1, "id"),
    HOST((short)2, "host"),
    PORT((short)3, "port"),
    TABLE_COUNT((short)4, "tableCount"),
    QPS1MIN((short)5, "qps1min"),
    CPU_USAGE((short)6, "cpuUsage"),
    MEM_USAGE((short)7, "memUsage"),
    LAST_HEARTBEAT((short)8, "lastHeartbeat");

    private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // ID
          return ID;
        case 2: // HOST
          return HOST;
        case 3: // PORT
          return PORT;
        case 4: // TABLE_COUNT
          return TABLE_COUNT;
        case 5: // QPS1MIN
          return QPS1MIN;
        case 6: // CPU_USAGE
          return CPU_USAGE;
        case 7: // MEM_USAGE
          return MEM_USAGE;
        case 8: // LAST_HEARTBEAT
          return LAST_HEARTBEAT;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __PORT_ISSET_ID = 0;
  private static final int __TABLECOUNT_ISSET_ID = 1;
  private static final int __QPS1MIN_ISSET_ID = 2;
  private static final int __CPUUSAGE_ISSET_ID = 3;
  private static final int __MEMUSAGE_ISSET_ID = 4;
  private static final int __LASTHEARTBEAT_ISSET_ID = 5;
  private byte __isset_bitfield = 0;
  private static final _Fields optionals[] = {_Fields.TABLE_COUNT,_Fields.QPS1MIN,_Fields.CPU_USAGE,_Fields.MEM_USAGE,_Fields.LAST_HEARTBEAT};
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.ID, new org.apache.thrift.meta_data.FieldMetaData("id", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.HOST, new org.apache.thrift.meta_data.FieldMetaData("host", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.PORT, new org.apache.thrift.meta_data.FieldMetaData("port", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.TABLE_COUNT, new org.apache.thrift.meta_data.FieldMetaData("tableCount", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.QPS1MIN, new org.apache.thrift.meta_data.FieldMetaData("qps1min", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.DOUBLE)));
    tmpMap.put(_Fields.CPU_USAGE, new org.apache.thrift.meta_data.FieldMetaData("cpuUsage", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.DOUBLE)));
    tmpMap.put(_Fields.MEM_USAGE, new org.apache.thrift.meta_data.FieldMetaData("memUsage", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.DOUBLE)));
    tmpMap.put(_Fields.LAST_HEARTBEAT, new org.apache.thrift.meta_data.FieldMetaData("lastHeartbeat", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64)));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(RegionServerInfo.class, metaDataMap);
  }

  public RegionServerInfo() {
  }

  public RegionServerInfo(
    java.lang.String id,
    java.lang.String host,
    int port)
  {
    this();
    this.id = id;
    this.host = host;
    this.port = port;
    setPortIsSet(true);
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public RegionServerInfo(RegionServerInfo other) {
    __isset_bitfield = other.__isset_bitfield;
    if (other.isSetId()) {
      this.id = other.id;
    }
    if (other.isSetHost()) {
      this.host = other.host;
    }
    this.port = other.port;
    this.tableCount = other.tableCount;
    this.qps1min = other.qps1min;
    this.cpuUsage = other.cpuUsage;
    this.memUsage = other.memUsage;
    this.lastHeartbeat = other.lastHeartbeat;
  }

  public RegionServerInfo deepCopy() {
    return new RegionServerInfo(this);
  }

  @Override
  public void clear() {
    this.id = null;
    this.host = null;
    setPortIsSet(false);
    this.port = 0;
    setTableCountIsSet(false);
    this.tableCount = 0;
    setQps1minIsSet(false);
    this.qps1min = 0.0;
    setCpuUsageIsSet(false);
    this.cpuUsage = 0.0;
    setMemUsageIsSet(false);
    this.memUsage = 0.0;
    setLastHeartbeatIsSet(false);
    this.lastHeartbeat = 0;
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.String getId() {
    return this.id;
  }

  public void setId(@org.apache.thrift.annotation.Nullable java.lang.String id) {
    this.id = id;
  }

  public void unsetId() {
    this.id = null;
  }

  /** Returns true if field id is set (has been assigned a value) and false otherwise */
  public boolean isSetId() {
    return this.id != null;
  }

  public void setIdIsSet(boolean value) {
    if (!value) {
      this.id = null;
    }
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.String getHost() {
    return this.host;
  }

  public void setHost(@org.apache.thrift.annotation.Nullable java.lang.String host) {
    this.host = host;
  }

  public void unsetHost() {
    this.host = null;
  }

  /** Returns true if field host is set (has been assigned a value) and false otherwise */
  public boolean isSetHost() {
    return this.host != null;
  }

  public void setHostIsSet(boolean value) {
    if (!value) {
      this.host = null;
    }
  }

  public int getPort() {
    return this.port;
  }

  public void setPort(int port) {
    this.port = port;
    setPortIsSet(true);
  }

  public void unsetPort() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __PORT_ISSET_ID);
  }

  /** Returns true if field port is set (has been assigned a value) and false otherwise */
  public boolean isSetPort() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __PORT_ISSET_ID);
  }

  public void setPortIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __PORT_ISSET_ID, value);
  }

  public int getTableCount() {
    return this.tableCount;
  }

  public void setTableCount(int tableCount) {
    this.tableCount = tableCount;
    setTableCountIsSet(true);
  }

  public void unsetTableCount() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __TABLECOUNT_ISSET_ID);
  }

  /** Returns true if field tableCount is set (has been assigned a value) and false otherwise */
  public boolean isSetTableCount() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __TABLECOUNT_ISSET_ID);
  }

  public void setTableCountIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __TABLECOUNT_ISSET_ID, value);
  }

  public double getQps1min() {
    return this.qps1min;
  }

  public void setQps1min(double qps1min) {
    this.qps1min = qps1min;
    setQps1minIsSet(true);
  }

  public void unsetQps1min() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __QPS1MIN_ISSET_ID);
  }

  /** Returns true if field qps1min is set (has been assigned a value) and false otherwise */
  public boolean isSetQps1min() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __QPS1MIN_ISSET_ID);
  }

  public void setQps1minIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __QPS1MIN_ISSET_ID, value);
  }

  public double getCpuUsage() {
    return this.cpuUsage;
  }

  public void setCpuUsage(double cpuUsage) {
    this.cpuUsage = cpuUsage;
    setCpuUsageIsSet(true);
  }

  public void unsetCpuUsage() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __CPUUSAGE_ISSET_ID);
  }

  /** Returns true if field cpuUsage is set (has been assigned a value) and false otherwise */
  public boolean isSetCpuUsage() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __CPUUSAGE_ISSET_ID);
  }

  public void setCpuUsageIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __CPUUSAGE_ISSET_ID, value);
  }

  public double getMemUsage() {
    return this.memUsage;
  }

  public void setMemUsage(double memUsage) {
    this.memUsage = memUsage;
    setMemUsageIsSet(true);
  }

  public void unsetMemUsage() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __MEMUSAGE_ISSET_ID);
  }

  /** Returns true if field memUsage is set (has been assigned a value) and false otherwise */
  public boolean isSetMemUsage() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __MEMUSAGE_ISSET_ID);
  }

  public void setMemUsageIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __MEMUSAGE_ISSET_ID, value);
  }

  public long getLastHeartbeat() {
    return this.lastHeartbeat;
  }

  public void setLastHeartbeat(long lastHeartbeat) {
    this.lastHeartbeat = lastHeartbeat;
    setLastHeartbeatIsSet(true);
  }

  public void unsetLastHeartbeat() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __LASTHEARTBEAT_ISSET_ID);
  }

  /** Returns true if field lastHeartbeat is set (has been assigned a value) and false otherwise */
  public boolean isSetLastHeartbeat() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __LASTHEARTBEAT_ISSET_ID);
  }

  public void setLastHeartbeatIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __LASTHEARTBEAT_ISSET_ID, value);
  }

  public void setFieldValue(_Fields field, @org.apache.thrift.annotation.Nullable java.lang.Object value) {
    switch (field) {
    case ID:
      if (value == null) {
        unsetId();
      } else {
        setId((java.lang.String)value);
      }
      break;

    case HOST:
      if (value == null) {
        unsetHost();
      } else {
        setHost((java.lang.String)value);
      }
      break;

    case PORT:
      if (value == null) {
        unsetPort();
      } else {
        setPort((java.lang.Integer)value);
      }
      break;

    case TABLE_COUNT:
      if (value == null) {
        unsetTableCount();
      } else {
        setTableCount((java.lang.Integer)value);
      }
      break;

    case QPS1MIN:
      if (value == null) {
        unsetQps1min();
      } else {
        setQps1min((java.lang.Double)value);
      }
      break;

    case CPU_USAGE:
      if (value == null) {
        unsetCpuUsage();
      } else {
        setCpuUsage((java.lang.Double)value);
      }
      break;

    case MEM_USAGE:
      if (value == null) {
        unsetMemUsage();
      } else {
        setMemUsage((java.lang.Double)value);
      }
      break;

    case LAST_HEARTBEAT:
      if (value == null) {
        unsetLastHeartbeat();
      } else {
        setLastHeartbeat((java.lang.Long)value);
      }
      break;

    }
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.Object getFieldValue(_Fields field) {
    switch (field) {
    case ID:
      return getId();

    case HOST:
      return getHost();

    case PORT:
      return getPort();

    case TABLE_COUNT:
      return getTableCount();

    case QPS1MIN:
      return getQps1min();

    case CPU_USAGE:
      return getCpuUsage();

    case MEM_USAGE:
      return getMemUsage();

    case LAST_HEARTBEAT:
      return getLastHeartbeat();

    }
    throw new java.lang.IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new java.lang.IllegalArgumentException();
    }

    switch (field) {
    case ID:
      return isSetId();
    case HOST:
      return isSetHost();
    case PORT:
      return isSetPort();
    case TABLE_COUNT:
      return isSetTableCount();
    case QPS1MIN:
      return isSetQps1min();
    case CPU_USAGE:
      return isSetCpuUsage();
    case MEM_USAGE:
      return isSetMemUsage();
    case LAST_HEARTBEAT:
      return isSetLastHeartbeat();
    }
    throw new java.lang.IllegalStateException();
  }

  @Override
  public boolean equals(java.lang.Object that) {
    if (that instanceof RegionServerInfo)
      return this.equals((RegionServerInfo)that);
    return false;
  }

  public boolean equals(RegionServerInfo that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_id = true && this.isSetId();
    boolean that_present_id = true && that.isSetId();
    if (this_present_id || that_present_id) {
      if (!(this_present_id && that_present_id))
        return false;
      if (!this.id.equals(that.id))
        return false;
    }

    boolean this_present_host = true && this.isSetHost();
    boolean that_present_host = true && that.isSetHost();
    if (this_present_host || that_present_host) {
      if (!(this_present_host && that_present_host))
        return false;
      if (!this.host.equals(that.host))
        return false;
    }

    boolean this_present_port = true;
    boolean that_present_port = true;
    if (this_present_port || that_present_port) {
      if (!(this_present_port && that_present_port))
        return false;
      if (this.port != that.port)
        return false;
    }

    boolean this_present_tableCount = true && this.isSetTableCount();
    boolean that_present_tableCount = true && that.isSetTableCount();
    if (this_present_tableCount || that_present_tableCount) {
      if (!(this_present_tableCount && that_present_tableCount))
        return false;
      if (this.tableCount != that.tableCount)
        return false;
    }

    boolean this_present_qps1min = true && this.isSetQps1min();
    boolean that_present_qps1min = true && that.isSetQps1min();
    if (this_present_qps1min || that_present_qps1min) {
      if (!(this_present_qps1min && that_present_qps1min))
        return false;
      if (this.qps1min != that.qps1min)
        return false;
    }

    boolean this_present_cpuUsage = true && this.isSetCpuUsage();
    boolean that_present_cpuUsage = true && that.isSetCpuUsage();
    if (this_present_cpuUsage || that_present_cpuUsage) {
      if (!(this_present_cpuUsage && that_present_cpuUsage))
        return false;
      if (this.cpuUsage != that.cpuUsage)
        return false;
    }

    boolean this_present_memUsage = true && this.isSetMemUsage();
    boolean that_present_memUsage = true && that.isSetMemUsage();
    if (this_present_memUsage || that_present_memUsage) {
      if (!(this_present_memUsage && that_present_memUsage))
        return false;
      if (this.memUsage != that.memUsage)
        return false;
    }

    boolean this_present_lastHeartbeat = true && this.isSetLastHeartbeat();
    boolean that_present_lastHeartbeat = true && that.isSetLastHeartbeat();
    if (this_present_lastHeartbeat || that_present_lastHeartbeat) {
      if (!(this_present_lastHeartbeat && that_present_lastHeartbeat))
        return false;
      if (this.lastHeartbeat != that.lastHeartbeat)
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + ((isSetId()) ? 131071 : 524287);
    if (isSetId())
      hashCode = hashCode * 8191 + id.hashCode();

    hashCode = hashCode * 8191 + ((isSetHost()) ? 131071 : 524287);
    if (isSetHost())
      hashCode = hashCode * 8191 + host.hashCode();

    hashCode = hashCode * 8191 + port;

    hashCode = hashCode * 8191 + ((isSetTableCount()) ? 131071 : 524287);
    if (isSetTableCount())
      hashCode = hashCode * 8191 + tableCount;

    hashCode = hashCode * 8191 + ((isSetQps1min()) ? 131071 : 524287);
    if (isSetQps1min())
      hashCode = hashCode * 8191 + org.apache.thrift.TBaseHelper.hashCode(qps1min);

    hashCode = hashCode * 8191 + ((isSetCpuUsage()) ? 131071 : 524287);
    if (isSetCpuUsage())
      hashCode = hashCode * 8191 + org.apache.thrift.TBaseHelper.hashCode(cpuUsage);

    hashCode = hashCode * 8191 + ((isSetMemUsage()) ? 131071 : 524287);
    if (isSetMemUsage())
      hashCode = hashCode * 8191 + org.apache.thrift.TBaseHelper.hashCode(memUsage);

    hashCode = hashCode * 8191 + ((isSetLastHeartbeat()) ? 131071 : 524287);
    if (isSetLastHeartbeat())
      hashCode = hashCode * 8191 + org.apache.thrift.TBaseHelper.hashCode(lastHeartbeat);

    return hashCode;
  }

  @Override
  public int compareTo(RegionServerInfo other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = java.lang.Boolean.compare(isSetId(), other.isSetId());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetId()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.id, other.id);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetHost(), other.isSetHost());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetHost()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.host, other.host);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetPort(), other.isSetPort());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetPort()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.port, other.port);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetTableCount(), other.isSetTableCount());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetTableCount()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.tableCount, other.tableCount);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetQps1min(), other.isSetQps1min());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetQps1min()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.qps1min, other.qps1min);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetCpuUsage(), other.isSetCpuUsage());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetCpuUsage()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.cpuUsage, other.cpuUsage);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetMemUsage(), other.isSetMemUsage());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetMemUsage()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.memUsage, other.memUsage);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetLastHeartbeat(), other.isSetLastHeartbeat());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetLastHeartbeat()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.lastHeartbeat, other.lastHeartbeat);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  @org.apache.thrift.annotation.Nullable
  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public java.lang.String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder("RegionServerInfo(");
    boolean first = true;

    sb.append("id:");
    if (this.id == null) {
      sb.append("null");
    } else {
      sb.append(this.id);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("host:");
    if (this.host == null) {
      sb.append("null");
    } else {
      sb.append(this.host);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("port:");
    sb.append(this.port);
    first = false;
    if (isSetTableCount()) {
      if (!first) sb.append(", ");
      sb.append("tableCount:");
      sb.append(this.tableCount);
      first = false;
    }
    if (isSetQps1min()) {
      if (!first) sb.append(", ");
      sb.append("qps1min:");
      sb.append(this.qps1min);
      first = false;
    }
    if (isSetCpuUsage()) {
      if (!first) sb.append(", ");
      sb.append("cpuUsage:");
      sb.append(this.cpuUsage);
      first = false;
    }
    if (isSetMemUsage()) {
      if (!first) sb.append(", ");
      sb.append("memUsage:");
      sb.append(this.memUsage);
      first = false;
    }
    if (isSetLastHeartbeat()) {
      if (!first) sb.append(", ");
      sb.append("lastHeartbeat:");
      sb.append(this.lastHeartbeat);
      first = false;
    }
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    if (!isSetId()) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'id' is unset! Struct:" + toString());
    }

    if (!isSetHost()) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'host' is unset! Struct:" + toString());
    }

    if (!isSetPort()) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'port' is unset! Struct:" + toString());
    }

    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class RegionServerInfoStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public RegionServerInfoStandardScheme getScheme() {
      return new RegionServerInfoStandardScheme();
    }
  }

  private static class RegionServerInfoStandardScheme extends org.apache.thrift.scheme.StandardScheme<RegionServerInfo> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, RegionServerInfo struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // ID
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.id = iprot.readString();
              struct.setIdIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // HOST
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.host = iprot.readString();
              struct.setHostIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // PORT
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.port = iprot.readI32();
              struct.setPortIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 4: // TABLE_COUNT
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.tableCount = iprot.readI32();
              struct.setTableCountIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 5: // QPS1MIN
            if (schemeField.type == org.apache.thrift.protocol.TType.DOUBLE) {
              struct.qps1min = iprot.readDouble();
              struct.setQps1minIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 6: // CPU_USAGE
            if (schemeField.type == org.apache.thrift.protocol.TType.DOUBLE) {
              struct.cpuUsage = iprot.readDouble();
              struct.setCpuUsageIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 7: // MEM_USAGE
            if (schemeField.type == org.apache.thrift.protocol.TType.DOUBLE) {
              struct.memUsage = iprot.readDouble();
              struct.setMemUsageIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 8: // LAST_HEARTBEAT
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.lastHeartbeat = iprot.readI64();
              struct.setLastHeartbeatIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, RegionServerInfo struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.id != null) {
        oprot.writeFieldBegin(ID_FIELD_DESC);
        oprot.writeString(struct.id);
        oprot.writeFieldEnd();
      }
      if (struct.host != null) {
        oprot.writeFieldBegin(HOST_FIELD_DESC);
        oprot.writeString(struct.host);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldBegin(PORT_FIELD_DESC);
      oprot.writeI32(struct.port);
      oprot.writeFieldEnd();
      if (struct.isSetTableCount()) {
        oprot.writeFieldBegin(TABLE_COUNT_FIELD_DESC);
        oprot.writeI32(struct.tableCount);
        oprot.writeFieldEnd();
      }
      if (struct.isSetQps1min()) {
        oprot.writeFieldBegin(QPS1MIN_FIELD_DESC);
        oprot.writeDouble(struct.qps1min);
        oprot.writeFieldEnd();
      }
      if (struct.isSetCpuUsage()) {
        oprot.writeFieldBegin(CPU_USAGE_FIELD_DESC);
        oprot.writeDouble(struct.cpuUsage);
        oprot.writeFieldEnd();
      }
      if (struct.isSetMemUsage()) {
        oprot.writeFieldBegin(MEM_USAGE_FIELD_DESC);
        oprot.writeDouble(struct.memUsage);
        oprot.writeFieldEnd();
      }
      if (struct.isSetLastHeartbeat()) {
        oprot.writeFieldBegin(LAST_HEARTBEAT_FIELD_DESC);
        oprot.writeI64(struct.lastHeartbeat);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class RegionServerInfoTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public RegionServerInfoTupleScheme getScheme() {
      return new RegionServerInfoTupleScheme();
    }
  }

  private static class RegionServerInfoTupleScheme extends org.apache.thrift.scheme.TupleScheme<RegionServerInfo> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, RegionServerInfo struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      oprot.writeString(struct.id);
      oprot.writeString(struct.host);
      oprot.writeI32(struct.port);
      java.util.BitSet optionals = new java.util.BitSet();
      if (struct.isSetTableCount()) {
        optionals.set(0);
      }
      if (struct.isSetQps1min()) {
        optionals.set(1);
      }
      if (struct.isSetCpuUsage()) {
        optionals.set(2);
      }
      if (struct.isSetMemUsage()) {
        optionals.set(3);
      }
      if (struct.isSetLastHeartbeat()) {
        optionals.set(4);
      }
      oprot.writeBitSet(optionals, 5);
      if (struct.isSetTableCount()) {
        oprot.writeI32(struct.tableCount);
      }
      if (struct.isSetQps1min()) {
        oprot.writeDouble(struct.qps1min);
      }
      if (struct.isSetCpuUsage()) {
        oprot.writeDouble(struct.cpuUsage);
      }
      if (struct.isSetMemUsage()) {
        oprot.writeDouble(struct.memUsage);
      }
      if (struct.isSetLastHeartbeat()) {
        oprot.writeI64(struct.lastHeartbeat);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, RegionServerInfo struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      struct.id = iprot.readString();
      struct.setIdIsSet(true);
      struct.host = iprot.readString();
      struct.setHostIsSet(true);
      struct.port = iprot.readI32();
      struct.setPortIsSet(true);
      java.util.BitSet incoming = iprot.readBitSet(5);
      if (incoming.get(0)) {
        struct.tableCount = iprot.readI32();
        struct.setTableCountIsSet(true);
      }
      if (incoming.get(1)) {
        struct.qps1min = iprot.readDouble();
        struct.setQps1minIsSet(true);
      }
      if (incoming.get(2)) {
        struct.cpuUsage = iprot.readDouble();
        struct.setCpuUsageIsSet(true);
      }
      if (incoming.get(3)) {
        struct.memUsage = iprot.readDouble();
        struct.setMemUsageIsSet(true);
      }
      if (incoming.get(4)) {
        struct.lastHeartbeat = iprot.readI64();
        struct.setLastHeartbeatIsSet(true);
      }
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

