/**
 * Autogenerated by Thrift Compiler (0.16.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package edu.zju.supersql.rpc;


/**
 * 操作结果状态码
 */
@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.16.0)", date = "2026-04-08")
public enum StatusCode implements org.apache.thrift.TEnum {
  OK(0),
  ERROR(1),
  TABLE_NOT_FOUND(2),
  TABLE_EXISTS(3),
  RS_NOT_FOUND(4),
  REDIRECT(5),
  MOVING(6),
  NOT_LEADER(7),
  REPLICA_TIMEOUT(8);

  private final int value;

  private StatusCode(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  @org.apache.thrift.annotation.Nullable
  public static StatusCode findByValue(int value) { 
    switch (value) {
      case 0:
        return OK;
      case 1:
        return ERROR;
      case 2:
        return TABLE_NOT_FOUND;
      case 3:
        return TABLE_EXISTS;
      case 4:
        return RS_NOT_FOUND;
      case 5:
        return REDIRECT;
      case 6:
        return MOVING;
      case 7:
        return NOT_LEADER;
      case 8:
        return REPLICA_TIMEOUT;
      default:
        return null;
    }
  }
}
