/**
 * Autogenerated by Thrift Compiler (0.16.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package edu.zju.supersql.rpc;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
/**
 * 表的路由元数据
 */
@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.16.0)", date = "2026-04-08")
public class TableLocation implements org.apache.thrift.TBase<TableLocation, TableLocation._Fields>, java.io.Serializable, Cloneable, Comparable<TableLocation> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("TableLocation");

  private static final org.apache.thrift.protocol.TField TABLE_NAME_FIELD_DESC = new org.apache.thrift.protocol.TField("tableName", org.apache.thrift.protocol.TType.STRING, (short)1);
  private static final org.apache.thrift.protocol.TField PRIMARY_RS_FIELD_DESC = new org.apache.thrift.protocol.TField("primaryRS", org.apache.thrift.protocol.TType.STRUCT, (short)2);
  private static final org.apache.thrift.protocol.TField REPLICAS_FIELD_DESC = new org.apache.thrift.protocol.TField("replicas", org.apache.thrift.protocol.TType.LIST, (short)3);
  private static final org.apache.thrift.protocol.TField TABLE_STATUS_FIELD_DESC = new org.apache.thrift.protocol.TField("tableStatus", org.apache.thrift.protocol.TType.STRING, (short)4);
  private static final org.apache.thrift.protocol.TField VERSION_FIELD_DESC = new org.apache.thrift.protocol.TField("version", org.apache.thrift.protocol.TType.I64, (short)5);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new TableLocationStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new TableLocationTupleSchemeFactory();

  private @org.apache.thrift.annotation.Nullable java.lang.String tableName; // required
  private @org.apache.thrift.annotation.Nullable RegionServerInfo primaryRS; // required
  private @org.apache.thrift.annotation.Nullable java.util.List<RegionServerInfo> replicas; // required
  private @org.apache.thrift.annotation.Nullable java.lang.String tableStatus; // optional
  private long version; // optional

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    TABLE_NAME((short)1, "tableName"),
    PRIMARY_RS((short)2, "primaryRS"),
    REPLICAS((short)3, "replicas"),
    TABLE_STATUS((short)4, "tableStatus"),
    VERSION((short)5, "version");

    private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // TABLE_NAME
          return TABLE_NAME;
        case 2: // PRIMARY_RS
          return PRIMARY_RS;
        case 3: // REPLICAS
          return REPLICAS;
        case 4: // TABLE_STATUS
          return TABLE_STATUS;
        case 5: // VERSION
          return VERSION;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __VERSION_ISSET_ID = 0;
  private byte __isset_bitfield = 0;
  private static final _Fields optionals[] = {_Fields.TABLE_STATUS,_Fields.VERSION};
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.TABLE_NAME, new org.apache.thrift.meta_data.FieldMetaData("tableName", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.PRIMARY_RS, new org.apache.thrift.meta_data.FieldMetaData("primaryRS", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, RegionServerInfo.class)));
    tmpMap.put(_Fields.REPLICAS, new org.apache.thrift.meta_data.FieldMetaData("replicas", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
            new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, RegionServerInfo.class))));
    tmpMap.put(_Fields.TABLE_STATUS, new org.apache.thrift.meta_data.FieldMetaData("tableStatus", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.VERSION, new org.apache.thrift.meta_data.FieldMetaData("version", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64)));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(TableLocation.class, metaDataMap);
  }

  public TableLocation() {
  }

  public TableLocation(
    java.lang.String tableName,
    RegionServerInfo primaryRS,
    java.util.List<RegionServerInfo> replicas)
  {
    this();
    this.tableName = tableName;
    this.primaryRS = primaryRS;
    this.replicas = replicas;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public TableLocation(TableLocation other) {
    __isset_bitfield = other.__isset_bitfield;
    if (other.isSetTableName()) {
      this.tableName = other.tableName;
    }
    if (other.isSetPrimaryRS()) {
      this.primaryRS = new RegionServerInfo(other.primaryRS);
    }
    if (other.isSetReplicas()) {
      java.util.List<RegionServerInfo> __this__replicas = new java.util.ArrayList<RegionServerInfo>(other.replicas.size());
      for (RegionServerInfo other_element : other.replicas) {
        __this__replicas.add(new RegionServerInfo(other_element));
      }
      this.replicas = __this__replicas;
    }
    if (other.isSetTableStatus()) {
      this.tableStatus = other.tableStatus;
    }
    this.version = other.version;
  }

  public TableLocation deepCopy() {
    return new TableLocation(this);
  }

  @Override
  public void clear() {
    this.tableName = null;
    this.primaryRS = null;
    this.replicas = null;
    this.tableStatus = null;
    setVersionIsSet(false);
    this.version = 0;
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.String getTableName() {
    return this.tableName;
  }

  public void setTableName(@org.apache.thrift.annotation.Nullable java.lang.String tableName) {
    this.tableName = tableName;
  }

  public void unsetTableName() {
    this.tableName = null;
  }

  /** Returns true if field tableName is set (has been assigned a value) and false otherwise */
  public boolean isSetTableName() {
    return this.tableName != null;
  }

  public void setTableNameIsSet(boolean value) {
    if (!value) {
      this.tableName = null;
    }
  }

  @org.apache.thrift.annotation.Nullable
  public RegionServerInfo getPrimaryRS() {
    return this.primaryRS;
  }

  public void setPrimaryRS(@org.apache.thrift.annotation.Nullable RegionServerInfo primaryRS) {
    this.primaryRS = primaryRS;
  }

  public void unsetPrimaryRS() {
    this.primaryRS = null;
  }

  /** Returns true if field primaryRS is set (has been assigned a value) and false otherwise */
  public boolean isSetPrimaryRS() {
    return this.primaryRS != null;
  }

  public void setPrimaryRSIsSet(boolean value) {
    if (!value) {
      this.primaryRS = null;
    }
  }

  public int getReplicasSize() {
    return (this.replicas == null) ? 0 : this.replicas.size();
  }

  @org.apache.thrift.annotation.Nullable
  public java.util.Iterator<RegionServerInfo> getReplicasIterator() {
    return (this.replicas == null) ? null : this.replicas.iterator();
  }

  public void addToReplicas(RegionServerInfo elem) {
    if (this.replicas == null) {
      this.replicas = new java.util.ArrayList<RegionServerInfo>();
    }
    this.replicas.add(elem);
  }

  @org.apache.thrift.annotation.Nullable
  public java.util.List<RegionServerInfo> getReplicas() {
    return this.replicas;
  }

  public void setReplicas(@org.apache.thrift.annotation.Nullable java.util.List<RegionServerInfo> replicas) {
    this.replicas = replicas;
  }

  public void unsetReplicas() {
    this.replicas = null;
  }

  /** Returns true if field replicas is set (has been assigned a value) and false otherwise */
  public boolean isSetReplicas() {
    return this.replicas != null;
  }

  public void setReplicasIsSet(boolean value) {
    if (!value) {
      this.replicas = null;
    }
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.String getTableStatus() {
    return this.tableStatus;
  }

  public void setTableStatus(@org.apache.thrift.annotation.Nullable java.lang.String tableStatus) {
    this.tableStatus = tableStatus;
  }

  public void unsetTableStatus() {
    this.tableStatus = null;
  }

  /** Returns true if field tableStatus is set (has been assigned a value) and false otherwise */
  public boolean isSetTableStatus() {
    return this.tableStatus != null;
  }

  public void setTableStatusIsSet(boolean value) {
    if (!value) {
      this.tableStatus = null;
    }
  }

  public long getVersion() {
    return this.version;
  }

  public void setVersion(long version) {
    this.version = version;
    setVersionIsSet(true);
  }

  public void unsetVersion() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __VERSION_ISSET_ID);
  }

  /** Returns true if field version is set (has been assigned a value) and false otherwise */
  public boolean isSetVersion() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __VERSION_ISSET_ID);
  }

  public void setVersionIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __VERSION_ISSET_ID, value);
  }

  public void setFieldValue(_Fields field, @org.apache.thrift.annotation.Nullable java.lang.Object value) {
    switch (field) {
    case TABLE_NAME:
      if (value == null) {
        unsetTableName();
      } else {
        setTableName((java.lang.String)value);
      }
      break;

    case PRIMARY_RS:
      if (value == null) {
        unsetPrimaryRS();
      } else {
        setPrimaryRS((RegionServerInfo)value);
      }
      break;

    case REPLICAS:
      if (value == null) {
        unsetReplicas();
      } else {
        setReplicas((java.util.List<RegionServerInfo>)value);
      }
      break;

    case TABLE_STATUS:
      if (value == null) {
        unsetTableStatus();
      } else {
        setTableStatus((java.lang.String)value);
      }
      break;

    case VERSION:
      if (value == null) {
        unsetVersion();
      } else {
        setVersion((java.lang.Long)value);
      }
      break;

    }
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.Object getFieldValue(_Fields field) {
    switch (field) {
    case TABLE_NAME:
      return getTableName();

    case PRIMARY_RS:
      return getPrimaryRS();

    case REPLICAS:
      return getReplicas();

    case TABLE_STATUS:
      return getTableStatus();

    case VERSION:
      return getVersion();

    }
    throw new java.lang.IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new java.lang.IllegalArgumentException();
    }

    switch (field) {
    case TABLE_NAME:
      return isSetTableName();
    case PRIMARY_RS:
      return isSetPrimaryRS();
    case REPLICAS:
      return isSetReplicas();
    case TABLE_STATUS:
      return isSetTableStatus();
    case VERSION:
      return isSetVersion();
    }
    throw new java.lang.IllegalStateException();
  }

  @Override
  public boolean equals(java.lang.Object that) {
    if (that instanceof TableLocation)
      return this.equals((TableLocation)that);
    return false;
  }

  public boolean equals(TableLocation that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_tableName = true && this.isSetTableName();
    boolean that_present_tableName = true && that.isSetTableName();
    if (this_present_tableName || that_present_tableName) {
      if (!(this_present_tableName && that_present_tableName))
        return false;
      if (!this.tableName.equals(that.tableName))
        return false;
    }

    boolean this_present_primaryRS = true && this.isSetPrimaryRS();
    boolean that_present_primaryRS = true && that.isSetPrimaryRS();
    if (this_present_primaryRS || that_present_primaryRS) {
      if (!(this_present_primaryRS && that_present_primaryRS))
        return false;
      if (!this.primaryRS.equals(that.primaryRS))
        return false;
    }

    boolean this_present_replicas = true && this.isSetReplicas();
    boolean that_present_replicas = true && that.isSetReplicas();
    if (this_present_replicas || that_present_replicas) {
      if (!(this_present_replicas && that_present_replicas))
        return false;
      if (!this.replicas.equals(that.replicas))
        return false;
    }

    boolean this_present_tableStatus = true && this.isSetTableStatus();
    boolean that_present_tableStatus = true && that.isSetTableStatus();
    if (this_present_tableStatus || that_present_tableStatus) {
      if (!(this_present_tableStatus && that_present_tableStatus))
        return false;
      if (!this.tableStatus.equals(that.tableStatus))
        return false;
    }

    boolean this_present_version = true && this.isSetVersion();
    boolean that_present_version = true && that.isSetVersion();
    if (this_present_version || that_present_version) {
      if (!(this_present_version && that_present_version))
        return false;
      if (this.version != that.version)
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + ((isSetTableName()) ? 131071 : 524287);
    if (isSetTableName())
      hashCode = hashCode * 8191 + tableName.hashCode();

    hashCode = hashCode * 8191 + ((isSetPrimaryRS()) ? 131071 : 524287);
    if (isSetPrimaryRS())
      hashCode = hashCode * 8191 + primaryRS.hashCode();

    hashCode = hashCode * 8191 + ((isSetReplicas()) ? 131071 : 524287);
    if (isSetReplicas())
      hashCode = hashCode * 8191 + replicas.hashCode();

    hashCode = hashCode * 8191 + ((isSetTableStatus()) ? 131071 : 524287);
    if (isSetTableStatus())
      hashCode = hashCode * 8191 + tableStatus.hashCode();

    hashCode = hashCode * 8191 + ((isSetVersion()) ? 131071 : 524287);
    if (isSetVersion())
      hashCode = hashCode * 8191 + org.apache.thrift.TBaseHelper.hashCode(version);

    return hashCode;
  }

  @Override
  public int compareTo(TableLocation other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = java.lang.Boolean.compare(isSetTableName(), other.isSetTableName());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetTableName()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.tableName, other.tableName);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetPrimaryRS(), other.isSetPrimaryRS());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetPrimaryRS()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.primaryRS, other.primaryRS);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetReplicas(), other.isSetReplicas());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetReplicas()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.replicas, other.replicas);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetTableStatus(), other.isSetTableStatus());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetTableStatus()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.tableStatus, other.tableStatus);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetVersion(), other.isSetVersion());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetVersion()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.version, other.version);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  @org.apache.thrift.annotation.Nullable
  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public java.lang.String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder("TableLocation(");
    boolean first = true;

    sb.append("tableName:");
    if (this.tableName == null) {
      sb.append("null");
    } else {
      sb.append(this.tableName);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("primaryRS:");
    if (this.primaryRS == null) {
      sb.append("null");
    } else {
      sb.append(this.primaryRS);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("replicas:");
    if (this.replicas == null) {
      sb.append("null");
    } else {
      sb.append(this.replicas);
    }
    first = false;
    if (isSetTableStatus()) {
      if (!first) sb.append(", ");
      sb.append("tableStatus:");
      if (this.tableStatus == null) {
        sb.append("null");
      } else {
        sb.append(this.tableStatus);
      }
      first = false;
    }
    if (isSetVersion()) {
      if (!first) sb.append(", ");
      sb.append("version:");
      sb.append(this.version);
      first = false;
    }
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    if (!isSetTableName()) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'tableName' is unset! Struct:" + toString());
    }

    if (!isSetPrimaryRS()) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'primaryRS' is unset! Struct:" + toString());
    }

    if (!isSetReplicas()) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'replicas' is unset! Struct:" + toString());
    }

    // check for sub-struct validity
    if (primaryRS != null) {
      primaryRS.validate();
    }
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class TableLocationStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public TableLocationStandardScheme getScheme() {
      return new TableLocationStandardScheme();
    }
  }

  private static class TableLocationStandardScheme extends org.apache.thrift.scheme.StandardScheme<TableLocation> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, TableLocation struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // TABLE_NAME
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.tableName = iprot.readString();
              struct.setTableNameIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // PRIMARY_RS
            if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
              struct.primaryRS = new RegionServerInfo();
              struct.primaryRS.read(iprot);
              struct.setPrimaryRSIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // REPLICAS
            if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
              {
                org.apache.thrift.protocol.TList _list0 = iprot.readListBegin();
                struct.replicas = new java.util.ArrayList<RegionServerInfo>(_list0.size);
                @org.apache.thrift.annotation.Nullable RegionServerInfo _elem1;
                for (int _i2 = 0; _i2 < _list0.size; ++_i2)
                {
                  _elem1 = new RegionServerInfo();
                  _elem1.read(iprot);
                  struct.replicas.add(_elem1);
                }
                iprot.readListEnd();
              }
              struct.setReplicasIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 4: // TABLE_STATUS
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.tableStatus = iprot.readString();
              struct.setTableStatusIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 5: // VERSION
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.version = iprot.readI64();
              struct.setVersionIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, TableLocation struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.tableName != null) {
        oprot.writeFieldBegin(TABLE_NAME_FIELD_DESC);
        oprot.writeString(struct.tableName);
        oprot.writeFieldEnd();
      }
      if (struct.primaryRS != null) {
        oprot.writeFieldBegin(PRIMARY_RS_FIELD_DESC);
        struct.primaryRS.write(oprot);
        oprot.writeFieldEnd();
      }
      if (struct.replicas != null) {
        oprot.writeFieldBegin(REPLICAS_FIELD_DESC);
        {
          oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, struct.replicas.size()));
          for (RegionServerInfo _iter3 : struct.replicas)
          {
            _iter3.write(oprot);
          }
          oprot.writeListEnd();
        }
        oprot.writeFieldEnd();
      }
      if (struct.tableStatus != null) {
        if (struct.isSetTableStatus()) {
          oprot.writeFieldBegin(TABLE_STATUS_FIELD_DESC);
          oprot.writeString(struct.tableStatus);
          oprot.writeFieldEnd();
        }
      }
      if (struct.isSetVersion()) {
        oprot.writeFieldBegin(VERSION_FIELD_DESC);
        oprot.writeI64(struct.version);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class TableLocationTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public TableLocationTupleScheme getScheme() {
      return new TableLocationTupleScheme();
    }
  }

  private static class TableLocationTupleScheme extends org.apache.thrift.scheme.TupleScheme<TableLocation> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, TableLocation struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      oprot.writeString(struct.tableName);
      struct.primaryRS.write(oprot);
      {
        oprot.writeI32(struct.replicas.size());
        for (RegionServerInfo _iter4 : struct.replicas)
        {
          _iter4.write(oprot);
        }
      }
      java.util.BitSet optionals = new java.util.BitSet();
      if (struct.isSetTableStatus()) {
        optionals.set(0);
      }
      if (struct.isSetVersion()) {
        optionals.set(1);
      }
      oprot.writeBitSet(optionals, 2);
      if (struct.isSetTableStatus()) {
        oprot.writeString(struct.tableStatus);
      }
      if (struct.isSetVersion()) {
        oprot.writeI64(struct.version);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, TableLocation struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      struct.tableName = iprot.readString();
      struct.setTableNameIsSet(true);
      struct.primaryRS = new RegionServerInfo();
      struct.primaryRS.read(iprot);
      struct.setPrimaryRSIsSet(true);
      {
        org.apache.thrift.protocol.TList _list5 = iprot.readListBegin(org.apache.thrift.protocol.TType.STRUCT);
        struct.replicas = new java.util.ArrayList<RegionServerInfo>(_list5.size);
        @org.apache.thrift.annotation.Nullable RegionServerInfo _elem6;
        for (int _i7 = 0; _i7 < _list5.size; ++_i7)
        {
          _elem6 = new RegionServerInfo();
          _elem6.read(iprot);
          struct.replicas.add(_elem6);
        }
      }
      struct.setReplicasIsSet(true);
      java.util.BitSet incoming = iprot.readBitSet(2);
      if (incoming.get(0)) {
        struct.tableStatus = iprot.readString();
        struct.setTableStatusIsSet(true);
      }
      if (incoming.get(1)) {
        struct.version = iprot.readI64();
        struct.setVersionIsSet(true);
      }
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

