/**
 * Autogenerated by Thrift Compiler (0.16.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package edu.zju.supersql.rpc;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.16.0)", date = "2026-04-08")
public class WalEntry implements org.apache.thrift.TBase<WalEntry, WalEntry._Fields>, java.io.Serializable, Cloneable, Comparable<WalEntry> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("WalEntry");

  private static final org.apache.thrift.protocol.TField LSN_FIELD_DESC = new org.apache.thrift.protocol.TField("lsn", org.apache.thrift.protocol.TType.I64, (short)1);
  private static final org.apache.thrift.protocol.TField TXN_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("txnId", org.apache.thrift.protocol.TType.I64, (short)2);
  private static final org.apache.thrift.protocol.TField TABLE_NAME_FIELD_DESC = new org.apache.thrift.protocol.TField("tableName", org.apache.thrift.protocol.TType.STRING, (short)3);
  private static final org.apache.thrift.protocol.TField OP_TYPE_FIELD_DESC = new org.apache.thrift.protocol.TField("opType", org.apache.thrift.protocol.TType.I32, (short)4);
  private static final org.apache.thrift.protocol.TField BEFORE_ROW_FIELD_DESC = new org.apache.thrift.protocol.TField("beforeRow", org.apache.thrift.protocol.TType.STRING, (short)5);
  private static final org.apache.thrift.protocol.TField AFTER_ROW_FIELD_DESC = new org.apache.thrift.protocol.TField("afterRow", org.apache.thrift.protocol.TType.STRING, (short)6);
  private static final org.apache.thrift.protocol.TField TIMESTAMP_FIELD_DESC = new org.apache.thrift.protocol.TField("timestamp", org.apache.thrift.protocol.TType.I64, (short)7);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new WalEntryStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new WalEntryTupleSchemeFactory();

  private long lsn; // required
  private long txnId; // required
  private @org.apache.thrift.annotation.Nullable java.lang.String tableName; // required
  private @org.apache.thrift.annotation.Nullable WalOpType opType; // required
  private @org.apache.thrift.annotation.Nullable java.nio.ByteBuffer beforeRow; // optional
  private @org.apache.thrift.annotation.Nullable java.nio.ByteBuffer afterRow; // optional
  private long timestamp; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    LSN((short)1, "lsn"),
    TXN_ID((short)2, "txnId"),
    TABLE_NAME((short)3, "tableName"),
    /**
     * 
     * @see WalOpType
     */
    OP_TYPE((short)4, "opType"),
    BEFORE_ROW((short)5, "beforeRow"),
    AFTER_ROW((short)6, "afterRow"),
    TIMESTAMP((short)7, "timestamp");

    private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // LSN
          return LSN;
        case 2: // TXN_ID
          return TXN_ID;
        case 3: // TABLE_NAME
          return TABLE_NAME;
        case 4: // OP_TYPE
          return OP_TYPE;
        case 5: // BEFORE_ROW
          return BEFORE_ROW;
        case 6: // AFTER_ROW
          return AFTER_ROW;
        case 7: // TIMESTAMP
          return TIMESTAMP;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __LSN_ISSET_ID = 0;
  private static final int __TXNID_ISSET_ID = 1;
  private static final int __TIMESTAMP_ISSET_ID = 2;
  private byte __isset_bitfield = 0;
  private static final _Fields optionals[] = {_Fields.BEFORE_ROW,_Fields.AFTER_ROW};
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.LSN, new org.apache.thrift.meta_data.FieldMetaData("lsn", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64)));
    tmpMap.put(_Fields.TXN_ID, new org.apache.thrift.meta_data.FieldMetaData("txnId", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64)));
    tmpMap.put(_Fields.TABLE_NAME, new org.apache.thrift.meta_data.FieldMetaData("tableName", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.OP_TYPE, new org.apache.thrift.meta_data.FieldMetaData("opType", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.EnumMetaData(org.apache.thrift.protocol.TType.ENUM, WalOpType.class)));
    tmpMap.put(_Fields.BEFORE_ROW, new org.apache.thrift.meta_data.FieldMetaData("beforeRow", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING        , true)));
    tmpMap.put(_Fields.AFTER_ROW, new org.apache.thrift.meta_data.FieldMetaData("afterRow", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING        , true)));
    tmpMap.put(_Fields.TIMESTAMP, new org.apache.thrift.meta_data.FieldMetaData("timestamp", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64)));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(WalEntry.class, metaDataMap);
  }

  public WalEntry() {
  }

  public WalEntry(
    long lsn,
    long txnId,
    java.lang.String tableName,
    WalOpType opType,
    long timestamp)
  {
    this();
    this.lsn = lsn;
    setLsnIsSet(true);
    this.txnId = txnId;
    setTxnIdIsSet(true);
    this.tableName = tableName;
    this.opType = opType;
    this.timestamp = timestamp;
    setTimestampIsSet(true);
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public WalEntry(WalEntry other) {
    __isset_bitfield = other.__isset_bitfield;
    this.lsn = other.lsn;
    this.txnId = other.txnId;
    if (other.isSetTableName()) {
      this.tableName = other.tableName;
    }
    if (other.isSetOpType()) {
      this.opType = other.opType;
    }
    if (other.isSetBeforeRow()) {
      this.beforeRow = org.apache.thrift.TBaseHelper.copyBinary(other.beforeRow);
    }
    if (other.isSetAfterRow()) {
      this.afterRow = org.apache.thrift.TBaseHelper.copyBinary(other.afterRow);
    }
    this.timestamp = other.timestamp;
  }

  public WalEntry deepCopy() {
    return new WalEntry(this);
  }

  @Override
  public void clear() {
    setLsnIsSet(false);
    this.lsn = 0;
    setTxnIdIsSet(false);
    this.txnId = 0;
    this.tableName = null;
    this.opType = null;
    this.beforeRow = null;
    this.afterRow = null;
    setTimestampIsSet(false);
    this.timestamp = 0;
  }

  public long getLsn() {
    return this.lsn;
  }

  public void setLsn(long lsn) {
    this.lsn = lsn;
    setLsnIsSet(true);
  }

  public void unsetLsn() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __LSN_ISSET_ID);
  }

  /** Returns true if field lsn is set (has been assigned a value) and false otherwise */
  public boolean isSetLsn() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __LSN_ISSET_ID);
  }

  public void setLsnIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __LSN_ISSET_ID, value);
  }

  public long getTxnId() {
    return this.txnId;
  }

  public void setTxnId(long txnId) {
    this.txnId = txnId;
    setTxnIdIsSet(true);
  }

  public void unsetTxnId() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __TXNID_ISSET_ID);
  }

  /** Returns true if field txnId is set (has been assigned a value) and false otherwise */
  public boolean isSetTxnId() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __TXNID_ISSET_ID);
  }

  public void setTxnIdIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __TXNID_ISSET_ID, value);
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.String getTableName() {
    return this.tableName;
  }

  public void setTableName(@org.apache.thrift.annotation.Nullable java.lang.String tableName) {
    this.tableName = tableName;
  }

  public void unsetTableName() {
    this.tableName = null;
  }

  /** Returns true if field tableName is set (has been assigned a value) and false otherwise */
  public boolean isSetTableName() {
    return this.tableName != null;
  }

  public void setTableNameIsSet(boolean value) {
    if (!value) {
      this.tableName = null;
    }
  }

  /**
   * 
   * @see WalOpType
   */
  @org.apache.thrift.annotation.Nullable
  public WalOpType getOpType() {
    return this.opType;
  }

  /**
   * 
   * @see WalOpType
   */
  public void setOpType(@org.apache.thrift.annotation.Nullable WalOpType opType) {
    this.opType = opType;
  }

  public void unsetOpType() {
    this.opType = null;
  }

  /** Returns true if field opType is set (has been assigned a value) and false otherwise */
  public boolean isSetOpType() {
    return this.opType != null;
  }

  public void setOpTypeIsSet(boolean value) {
    if (!value) {
      this.opType = null;
    }
  }

  public byte[] getBeforeRow() {
    setBeforeRow(org.apache.thrift.TBaseHelper.rightSize(beforeRow));
    return beforeRow == null ? null : beforeRow.array();
  }

  public java.nio.ByteBuffer bufferForBeforeRow() {
    return org.apache.thrift.TBaseHelper.copyBinary(beforeRow);
  }

  public void setBeforeRow(byte[] beforeRow) {
    this.beforeRow = beforeRow == null ? (java.nio.ByteBuffer)null   : java.nio.ByteBuffer.wrap(beforeRow.clone());
  }

  public void setBeforeRow(@org.apache.thrift.annotation.Nullable java.nio.ByteBuffer beforeRow) {
    this.beforeRow = org.apache.thrift.TBaseHelper.copyBinary(beforeRow);
  }

  public void unsetBeforeRow() {
    this.beforeRow = null;
  }

  /** Returns true if field beforeRow is set (has been assigned a value) and false otherwise */
  public boolean isSetBeforeRow() {
    return this.beforeRow != null;
  }

  public void setBeforeRowIsSet(boolean value) {
    if (!value) {
      this.beforeRow = null;
    }
  }

  public byte[] getAfterRow() {
    setAfterRow(org.apache.thrift.TBaseHelper.rightSize(afterRow));
    return afterRow == null ? null : afterRow.array();
  }

  public java.nio.ByteBuffer bufferForAfterRow() {
    return org.apache.thrift.TBaseHelper.copyBinary(afterRow);
  }

  public void setAfterRow(byte[] afterRow) {
    this.afterRow = afterRow == null ? (java.nio.ByteBuffer)null   : java.nio.ByteBuffer.wrap(afterRow.clone());
  }

  public void setAfterRow(@org.apache.thrift.annotation.Nullable java.nio.ByteBuffer afterRow) {
    this.afterRow = org.apache.thrift.TBaseHelper.copyBinary(afterRow);
  }

  public void unsetAfterRow() {
    this.afterRow = null;
  }

  /** Returns true if field afterRow is set (has been assigned a value) and false otherwise */
  public boolean isSetAfterRow() {
    return this.afterRow != null;
  }

  public void setAfterRowIsSet(boolean value) {
    if (!value) {
      this.afterRow = null;
    }
  }

  public long getTimestamp() {
    return this.timestamp;
  }

  public void setTimestamp(long timestamp) {
    this.timestamp = timestamp;
    setTimestampIsSet(true);
  }

  public void unsetTimestamp() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __TIMESTAMP_ISSET_ID);
  }

  /** Returns true if field timestamp is set (has been assigned a value) and false otherwise */
  public boolean isSetTimestamp() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __TIMESTAMP_ISSET_ID);
  }

  public void setTimestampIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __TIMESTAMP_ISSET_ID, value);
  }

  public void setFieldValue(_Fields field, @org.apache.thrift.annotation.Nullable java.lang.Object value) {
    switch (field) {
    case LSN:
      if (value == null) {
        unsetLsn();
      } else {
        setLsn((java.lang.Long)value);
      }
      break;

    case TXN_ID:
      if (value == null) {
        unsetTxnId();
      } else {
        setTxnId((java.lang.Long)value);
      }
      break;

    case TABLE_NAME:
      if (value == null) {
        unsetTableName();
      } else {
        setTableName((java.lang.String)value);
      }
      break;

    case OP_TYPE:
      if (value == null) {
        unsetOpType();
      } else {
        setOpType((WalOpType)value);
      }
      break;

    case BEFORE_ROW:
      if (value == null) {
        unsetBeforeRow();
      } else {
        if (value instanceof byte[]) {
          setBeforeRow((byte[])value);
        } else {
          setBeforeRow((java.nio.ByteBuffer)value);
        }
      }
      break;

    case AFTER_ROW:
      if (value == null) {
        unsetAfterRow();
      } else {
        if (value instanceof byte[]) {
          setAfterRow((byte[])value);
        } else {
          setAfterRow((java.nio.ByteBuffer)value);
        }
      }
      break;

    case TIMESTAMP:
      if (value == null) {
        unsetTimestamp();
      } else {
        setTimestamp((java.lang.Long)value);
      }
      break;

    }
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.Object getFieldValue(_Fields field) {
    switch (field) {
    case LSN:
      return getLsn();

    case TXN_ID:
      return getTxnId();

    case TABLE_NAME:
      return getTableName();

    case OP_TYPE:
      return getOpType();

    case BEFORE_ROW:
      return getBeforeRow();

    case AFTER_ROW:
      return getAfterRow();

    case TIMESTAMP:
      return getTimestamp();

    }
    throw new java.lang.IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new java.lang.IllegalArgumentException();
    }

    switch (field) {
    case LSN:
      return isSetLsn();
    case TXN_ID:
      return isSetTxnId();
    case TABLE_NAME:
      return isSetTableName();
    case OP_TYPE:
      return isSetOpType();
    case BEFORE_ROW:
      return isSetBeforeRow();
    case AFTER_ROW:
      return isSetAfterRow();
    case TIMESTAMP:
      return isSetTimestamp();
    }
    throw new java.lang.IllegalStateException();
  }

  @Override
  public boolean equals(java.lang.Object that) {
    if (that instanceof WalEntry)
      return this.equals((WalEntry)that);
    return false;
  }

  public boolean equals(WalEntry that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_lsn = true;
    boolean that_present_lsn = true;
    if (this_present_lsn || that_present_lsn) {
      if (!(this_present_lsn && that_present_lsn))
        return false;
      if (this.lsn != that.lsn)
        return false;
    }

    boolean this_present_txnId = true;
    boolean that_present_txnId = true;
    if (this_present_txnId || that_present_txnId) {
      if (!(this_present_txnId && that_present_txnId))
        return false;
      if (this.txnId != that.txnId)
        return false;
    }

    boolean this_present_tableName = true && this.isSetTableName();
    boolean that_present_tableName = true && that.isSetTableName();
    if (this_present_tableName || that_present_tableName) {
      if (!(this_present_tableName && that_present_tableName))
        return false;
      if (!this.tableName.equals(that.tableName))
        return false;
    }

    boolean this_present_opType = true && this.isSetOpType();
    boolean that_present_opType = true && that.isSetOpType();
    if (this_present_opType || that_present_opType) {
      if (!(this_present_opType && that_present_opType))
        return false;
      if (!this.opType.equals(that.opType))
        return false;
    }

    boolean this_present_beforeRow = true && this.isSetBeforeRow();
    boolean that_present_beforeRow = true && that.isSetBeforeRow();
    if (this_present_beforeRow || that_present_beforeRow) {
      if (!(this_present_beforeRow && that_present_beforeRow))
        return false;
      if (!this.beforeRow.equals(that.beforeRow))
        return false;
    }

    boolean this_present_afterRow = true && this.isSetAfterRow();
    boolean that_present_afterRow = true && that.isSetAfterRow();
    if (this_present_afterRow || that_present_afterRow) {
      if (!(this_present_afterRow && that_present_afterRow))
        return false;
      if (!this.afterRow.equals(that.afterRow))
        return false;
    }

    boolean this_present_timestamp = true;
    boolean that_present_timestamp = true;
    if (this_present_timestamp || that_present_timestamp) {
      if (!(this_present_timestamp && that_present_timestamp))
        return false;
      if (this.timestamp != that.timestamp)
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + org.apache.thrift.TBaseHelper.hashCode(lsn);

    hashCode = hashCode * 8191 + org.apache.thrift.TBaseHelper.hashCode(txnId);

    hashCode = hashCode * 8191 + ((isSetTableName()) ? 131071 : 524287);
    if (isSetTableName())
      hashCode = hashCode * 8191 + tableName.hashCode();

    hashCode = hashCode * 8191 + ((isSetOpType()) ? 131071 : 524287);
    if (isSetOpType())
      hashCode = hashCode * 8191 + opType.getValue();

    hashCode = hashCode * 8191 + ((isSetBeforeRow()) ? 131071 : 524287);
    if (isSetBeforeRow())
      hashCode = hashCode * 8191 + beforeRow.hashCode();

    hashCode = hashCode * 8191 + ((isSetAfterRow()) ? 131071 : 524287);
    if (isSetAfterRow())
      hashCode = hashCode * 8191 + afterRow.hashCode();

    hashCode = hashCode * 8191 + org.apache.thrift.TBaseHelper.hashCode(timestamp);

    return hashCode;
  }

  @Override
  public int compareTo(WalEntry other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = java.lang.Boolean.compare(isSetLsn(), other.isSetLsn());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetLsn()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.lsn, other.lsn);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetTxnId(), other.isSetTxnId());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetTxnId()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.txnId, other.txnId);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetTableName(), other.isSetTableName());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetTableName()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.tableName, other.tableName);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetOpType(), other.isSetOpType());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetOpType()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.opType, other.opType);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetBeforeRow(), other.isSetBeforeRow());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetBeforeRow()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.beforeRow, other.beforeRow);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetAfterRow(), other.isSetAfterRow());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetAfterRow()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.afterRow, other.afterRow);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetTimestamp(), other.isSetTimestamp());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetTimestamp()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.timestamp, other.timestamp);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  @org.apache.thrift.annotation.Nullable
  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public java.lang.String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder("WalEntry(");
    boolean first = true;

    sb.append("lsn:");
    sb.append(this.lsn);
    first = false;
    if (!first) sb.append(", ");
    sb.append("txnId:");
    sb.append(this.txnId);
    first = false;
    if (!first) sb.append(", ");
    sb.append("tableName:");
    if (this.tableName == null) {
      sb.append("null");
    } else {
      sb.append(this.tableName);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("opType:");
    if (this.opType == null) {
      sb.append("null");
    } else {
      sb.append(this.opType);
    }
    first = false;
    if (isSetBeforeRow()) {
      if (!first) sb.append(", ");
      sb.append("beforeRow:");
      if (this.beforeRow == null) {
        sb.append("null");
      } else {
        org.apache.thrift.TBaseHelper.toString(this.beforeRow, sb);
      }
      first = false;
    }
    if (isSetAfterRow()) {
      if (!first) sb.append(", ");
      sb.append("afterRow:");
      if (this.afterRow == null) {
        sb.append("null");
      } else {
        org.apache.thrift.TBaseHelper.toString(this.afterRow, sb);
      }
      first = false;
    }
    if (!first) sb.append(", ");
    sb.append("timestamp:");
    sb.append(this.timestamp);
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    if (!isSetLsn()) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'lsn' is unset! Struct:" + toString());
    }

    if (!isSetTxnId()) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'txnId' is unset! Struct:" + toString());
    }

    if (!isSetTableName()) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'tableName' is unset! Struct:" + toString());
    }

    if (!isSetOpType()) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'opType' is unset! Struct:" + toString());
    }

    if (!isSetTimestamp()) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'timestamp' is unset! Struct:" + toString());
    }

    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class WalEntryStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public WalEntryStandardScheme getScheme() {
      return new WalEntryStandardScheme();
    }
  }

  private static class WalEntryStandardScheme extends org.apache.thrift.scheme.StandardScheme<WalEntry> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, WalEntry struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // LSN
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.lsn = iprot.readI64();
              struct.setLsnIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // TXN_ID
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.txnId = iprot.readI64();
              struct.setTxnIdIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // TABLE_NAME
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.tableName = iprot.readString();
              struct.setTableNameIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 4: // OP_TYPE
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.opType = edu.zju.supersql.rpc.WalOpType.findByValue(iprot.readI32());
              struct.setOpTypeIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 5: // BEFORE_ROW
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.beforeRow = iprot.readBinary();
              struct.setBeforeRowIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 6: // AFTER_ROW
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.afterRow = iprot.readBinary();
              struct.setAfterRowIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 7: // TIMESTAMP
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.timestamp = iprot.readI64();
              struct.setTimestampIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, WalEntry struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      oprot.writeFieldBegin(LSN_FIELD_DESC);
      oprot.writeI64(struct.lsn);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(TXN_ID_FIELD_DESC);
      oprot.writeI64(struct.txnId);
      oprot.writeFieldEnd();
      if (struct.tableName != null) {
        oprot.writeFieldBegin(TABLE_NAME_FIELD_DESC);
        oprot.writeString(struct.tableName);
        oprot.writeFieldEnd();
      }
      if (struct.opType != null) {
        oprot.writeFieldBegin(OP_TYPE_FIELD_DESC);
        oprot.writeI32(struct.opType.getValue());
        oprot.writeFieldEnd();
      }
      if (struct.beforeRow != null) {
        if (struct.isSetBeforeRow()) {
          oprot.writeFieldBegin(BEFORE_ROW_FIELD_DESC);
          oprot.writeBinary(struct.beforeRow);
          oprot.writeFieldEnd();
        }
      }
      if (struct.afterRow != null) {
        if (struct.isSetAfterRow()) {
          oprot.writeFieldBegin(AFTER_ROW_FIELD_DESC);
          oprot.writeBinary(struct.afterRow);
          oprot.writeFieldEnd();
        }
      }
      oprot.writeFieldBegin(TIMESTAMP_FIELD_DESC);
      oprot.writeI64(struct.timestamp);
      oprot.writeFieldEnd();
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class WalEntryTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public WalEntryTupleScheme getScheme() {
      return new WalEntryTupleScheme();
    }
  }

  private static class WalEntryTupleScheme extends org.apache.thrift.scheme.TupleScheme<WalEntry> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, WalEntry struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      oprot.writeI64(struct.lsn);
      oprot.writeI64(struct.txnId);
      oprot.writeString(struct.tableName);
      oprot.writeI32(struct.opType.getValue());
      oprot.writeI64(struct.timestamp);
      java.util.BitSet optionals = new java.util.BitSet();
      if (struct.isSetBeforeRow()) {
        optionals.set(0);
      }
      if (struct.isSetAfterRow()) {
        optionals.set(1);
      }
      oprot.writeBitSet(optionals, 2);
      if (struct.isSetBeforeRow()) {
        oprot.writeBinary(struct.beforeRow);
      }
      if (struct.isSetAfterRow()) {
        oprot.writeBinary(struct.afterRow);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, WalEntry struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      struct.lsn = iprot.readI64();
      struct.setLsnIsSet(true);
      struct.txnId = iprot.readI64();
      struct.setTxnIdIsSet(true);
      struct.tableName = iprot.readString();
      struct.setTableNameIsSet(true);
      struct.opType = edu.zju.supersql.rpc.WalOpType.findByValue(iprot.readI32());
      struct.setOpTypeIsSet(true);
      struct.timestamp = iprot.readI64();
      struct.setTimestampIsSet(true);
      java.util.BitSet incoming = iprot.readBitSet(2);
      if (incoming.get(0)) {
        struct.beforeRow = iprot.readBinary();
        struct.setBeforeRowIsSet(true);
      }
      if (incoming.get(1)) {
        struct.afterRow = iprot.readBinary();
        struct.setAfterRowIsSet(true);
      }
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

