/**
 * Autogenerated by Thrift Compiler (0.12.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package edu.zju.supersql.rpc;


/**
 * WAL 日志条目（用于副本同步）
 */
@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.12.0)", date = "2026-04-19")
public enum WalOpType implements org.apache.thrift.TEnum {
  INSERT(1),
  UPDATE(2),
  DELETE(3),
  CREATE_TABLE(4),
  DROP_TABLE(5),
  CREATE_INDEX(6),
  DROP_INDEX(7);

  private final int value;

  private WalOpType(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  @org.apache.thrift.annotation.Nullable
  public static WalOpType findByValue(int value) { 
    switch (value) {
      case 1:
        return INSERT;
      case 2:
        return UPDATE;
      case 3:
        return DELETE;
      case 4:
        return CREATE_TABLE;
      case 5:
        return DROP_TABLE;
      case 6:
        return CREATE_INDEX;
      case 7:
        return DROP_INDEX;
      default:
        return null;
    }
  }
}
